//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafaItemDetails.SafaItemDetailsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonAsUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SafaItemDetails.SafaItemDetailsService.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SafaItemDetails.SafaItemDetailsService.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SafaItemDetails.SafaItemDetailsService.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SafaItemDetails.SafaItemDetailsService.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SafaItemDetails.SafaItemDetailsService.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SafaItemDetails.SafaItemDetailsService.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SafaItemDetails.SafaItemDetailsService.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SafaItemDetails.SafaItemDetailsService.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="SafaItemDetailsService.ItemDetailsService")]
    public interface ItemDetailsService {
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGetItemBatchesRequest) of message ItemDetailsServiceGetItemBatchesRequest does not match the default value (getItemBatches)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getItemBatches", ReplyAction="http://tempuri.org/ItemDetailsService/getItemBatchesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/getItemBatchesAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesResponse getItemBatches(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getItemBatches", ReplyAction="http://tempuri.org/ItemDetailsService/getItemBatchesResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesResponse> getItemBatchesAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGeDetailsFromBarcodeRequest) of message ItemDetailsServiceGeDetailsFromBarcodeRequest does not match the default value (geDetailsFromBarcode)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/geDetailsFromBarcode", ReplyAction="http://tempuri.org/ItemDetailsService/geDetailsFromBarcodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/geDetailsFromBarcodeAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeResponse geDetailsFromBarcode(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/geDetailsFromBarcode", ReplyAction="http://tempuri.org/ItemDetailsService/geDetailsFromBarcodeResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeResponse> geDetailsFromBarcodeAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGetOpenTagCountJournalsRequest) of message ItemDetailsServiceGetOpenTagCountJournalsRequest does not match the default value (getOpenTagCountJournals)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getOpenTagCountJournals", ReplyAction="http://tempuri.org/ItemDetailsService/getOpenTagCountJournalsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/getOpenTagCountJournalsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsResponse getOpenTagCountJournals(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getOpenTagCountJournals", ReplyAction="http://tempuri.org/ItemDetailsService/getOpenTagCountJournalsResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsResponse> getOpenTagCountJournalsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceSafaCreateEmployeeRequest) of message ItemDetailsServiceSafaCreateEmployeeRequest does not match the default value (SafaCreateEmployee)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/SafaCreateEmployee", ReplyAction="http://tempuri.org/ItemDetailsService/SafaCreateEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/SafaCreateEmployeeAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeResponse SafaCreateEmployee(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/SafaCreateEmployee", ReplyAction="http://tempuri.org/ItemDetailsService/SafaCreateEmployeeResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeResponse> SafaCreateEmployeeAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGetCustomerPointsRequest) of message ItemDetailsServiceGetCustomerPointsRequest does not match the default value (getCustomerPoints)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getCustomerPoints", ReplyAction="http://tempuri.org/ItemDetailsService/getCustomerPointsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/getCustomerPointsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsResponse getCustomerPoints(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getCustomerPoints", ReplyAction="http://tempuri.org/ItemDetailsService/getCustomerPointsResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsResponse> getCustomerPointsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGetAllItemsRequest) of message ItemDetailsServiceGetAllItemsRequest does not match the default value (getAllItems)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getAllItems", ReplyAction="http://tempuri.org/ItemDetailsService/getAllItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/getAllItemsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsResponse getAllItems(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getAllItems", ReplyAction="http://tempuri.org/ItemDetailsService/getAllItemsResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsResponse> getAllItemsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGetItemDetailsRequest) of message ItemDetailsServiceGetItemDetailsRequest does not match the default value (getItemDetails)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getItemDetails", ReplyAction="http://tempuri.org/ItemDetailsService/getItemDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/getItemDetailsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsResponse getItemDetails(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getItemDetails", ReplyAction="http://tempuri.org/ItemDetailsService/getItemDetailsResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsResponse> getItemDetailsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceCreateTagCountLineRequest) of message ItemDetailsServiceCreateTagCountLineRequest does not match the default value (CreateTagCountLine)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/CreateTagCountLine", ReplyAction="http://tempuri.org/ItemDetailsService/CreateTagCountLineResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/CreateTagCountLineAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineResponse CreateTagCountLine(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/CreateTagCountLine", ReplyAction="http://tempuri.org/ItemDetailsService/CreateTagCountLineResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineResponse> CreateTagCountLineAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceEarnOrRedeemPointsRequest) of message ItemDetailsServiceEarnOrRedeemPointsRequest does not match the default value (earnOrRedeemPoints)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/earnOrRedeemPoints", ReplyAction="http://tempuri.org/ItemDetailsService/earnOrRedeemPointsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/earnOrRedeemPointsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsResponse earnOrRedeemPoints(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/earnOrRedeemPoints", ReplyAction="http://tempuri.org/ItemDetailsService/earnOrRedeemPointsResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsResponse> earnOrRedeemPointsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceCreateEmployeeRequest) of message ItemDetailsServiceCreateEmployeeRequest does not match the default value (CreateEmployee)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/CreateEmployee", ReplyAction="http://tempuri.org/ItemDetailsService/CreateEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.SafaItemDetailsService.AifFault), Action="http://tempuri.org/ItemDetailsService/CreateEmployeeAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeResponse CreateEmployee(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/CreateEmployee", ReplyAction="http://tempuri.org/ItemDetailsService/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeResponse> CreateEmployeeAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetItemBatchesRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetItemBatchesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _item;
        
        public ItemDetailsServiceGetItemBatchesRequest() {
        }
        
        public ItemDetailsServiceGetItemBatchesRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _item) {
            this.CallContext = CallContext;
            this._item = _item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetItemBatchesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetItemBatchesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGetItemBatchesResponse() {
        }
        
        public ItemDetailsServiceGetItemBatchesResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGeDetailsFromBarcodeRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGeDetailsFromBarcodeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string barcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _journal;
        
        public ItemDetailsServiceGeDetailsFromBarcodeRequest() {
        }
        
        public ItemDetailsServiceGeDetailsFromBarcodeRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string barcode, string _journal) {
            this.CallContext = CallContext;
            this.barcode = barcode;
            this._journal = _journal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGeDetailsFromBarcodeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGeDetailsFromBarcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGeDetailsFromBarcodeResponse() {
        }
        
        public ItemDetailsServiceGeDetailsFromBarcodeResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetOpenTagCountJournalsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetOpenTagCountJournalsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        public ItemDetailsServiceGetOpenTagCountJournalsRequest() {
        }
        
        public ItemDetailsServiceGetOpenTagCountJournalsRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetOpenTagCountJournalsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetOpenTagCountJournalsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGetOpenTagCountJournalsResponse() {
        }
        
        public ItemDetailsServiceGetOpenTagCountJournalsResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceSafaCreateEmployeeRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceSafaCreateEmployeeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string empId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string middleName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string dob;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=5)]
        public string joiningDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=6)]
        public bool isRetail;
        
        public ItemDetailsServiceSafaCreateEmployeeRequest() {
        }
        
        public ItemDetailsServiceSafaCreateEmployeeRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string empId, string firstName, string middleName, string lastName, string dob, string joiningDate, bool isRetail) {
            this.CallContext = CallContext;
            this.empId = empId;
            this.firstName = firstName;
            this.middleName = middleName;
            this.lastName = lastName;
            this.dob = dob;
            this.joiningDate = joiningDate;
            this.isRetail = isRetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceSafaCreateEmployeeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceSafaCreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceSafaCreateEmployeeResponse() {
        }
        
        public ItemDetailsServiceSafaCreateEmployeeResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetCustomerPointsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetCustomerPointsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _cust;
        
        public ItemDetailsServiceGetCustomerPointsRequest() {
        }
        
        public ItemDetailsServiceGetCustomerPointsRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _cust) {
            this.CallContext = CallContext;
            this._cust = _cust;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetCustomerPointsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetCustomerPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGetCustomerPointsResponse() {
        }
        
        public ItemDetailsServiceGetCustomerPointsResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetAllItemsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetAllItemsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        public ItemDetailsServiceGetAllItemsRequest() {
        }
        
        public ItemDetailsServiceGetAllItemsRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetAllItemsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetAllItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGetAllItemsResponse() {
        }
        
        public ItemDetailsServiceGetAllItemsResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetItemDetailsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetItemDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string itemId;
        
        public ItemDetailsServiceGetItemDetailsRequest() {
        }
        
        public ItemDetailsServiceGetItemDetailsRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string itemId) {
            this.CallContext = CallContext;
            this.itemId = itemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetItemDetailsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetItemDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGetItemDetailsResponse() {
        }
        
        public ItemDetailsServiceGetItemDetailsResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceCreateTagCountLineRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceCreateTagCountLineRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string journalNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _item;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _barcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public decimal _qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string _batch;
        
        public ItemDetailsServiceCreateTagCountLineRequest() {
        }
        
        public ItemDetailsServiceCreateTagCountLineRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string journalNum, string _item, string _barcode, decimal _qty, string _batch) {
            this.CallContext = CallContext;
            this.journalNum = journalNum;
            this._item = _item;
            this._barcode = _barcode;
            this._qty = _qty;
            this._batch = _batch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceCreateTagCountLineResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceCreateTagCountLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceCreateTagCountLineResponse() {
        }
        
        public ItemDetailsServiceCreateTagCountLineResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceEarnOrRedeemPointsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceEarnOrRedeemPointsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _cust;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _points;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _webOrderId;
        
        public ItemDetailsServiceEarnOrRedeemPointsRequest() {
        }
        
        public ItemDetailsServiceEarnOrRedeemPointsRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _cust, string _type, string _points, string _webOrderId) {
            this.CallContext = CallContext;
            this._cust = _cust;
            this._type = _type;
            this._points = _points;
            this._webOrderId = _webOrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceEarnOrRedeemPointsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceEarnOrRedeemPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceEarnOrRedeemPointsResponse() {
        }
        
        public ItemDetailsServiceEarnOrRedeemPointsResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceCreateEmployeeRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceCreateEmployeeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.SafaItemDetailsService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string empId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string middleName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string dob;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=5)]
        public string joiningDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=6)]
        public bool isRetail;
        
        public ItemDetailsServiceCreateEmployeeRequest() {
        }
        
        public ItemDetailsServiceCreateEmployeeRequest(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string empId, string firstName, string middleName, string lastName, string dob, string joiningDate, bool isRetail) {
            this.CallContext = CallContext;
            this.empId = empId;
            this.firstName = firstName;
            this.middleName = middleName;
            this.lastName = lastName;
            this.dob = dob;
            this.joiningDate = joiningDate;
            this.isRetail = isRetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceCreateEmployeeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceCreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceCreateEmployeeResponse() {
        }
        
        public ItemDetailsServiceCreateEmployeeResponse(string response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItemDetailsServiceChannel : SafaItemDetails.SafaItemDetailsService.ItemDetailsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemDetailsServiceClient : System.ServiceModel.ClientBase<SafaItemDetails.SafaItemDetailsService.ItemDetailsService>, SafaItemDetails.SafaItemDetailsService.ItemDetailsService {
        
        public ItemDetailsServiceClient() {
        }
        
        public ItemDetailsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemDetailsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemDetailsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getItemBatches(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesRequest request) {
            return base.Channel.getItemBatches(request);
        }
        
        public string getItemBatches(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _item) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesRequest();
            inValue.CallContext = CallContext;
            inValue._item = _item;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getItemBatches(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getItemBatchesAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesRequest request) {
            return base.Channel.getItemBatchesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesResponse> getItemBatchesAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _item) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemBatchesRequest();
            inValue.CallContext = CallContext;
            inValue._item = _item;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getItemBatchesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.geDetailsFromBarcode(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeRequest request) {
            return base.Channel.geDetailsFromBarcode(request);
        }
        
        public string geDetailsFromBarcode(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string barcode, string _journal) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeRequest();
            inValue.CallContext = CallContext;
            inValue.barcode = barcode;
            inValue._journal = _journal;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).geDetailsFromBarcode(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.geDetailsFromBarcodeAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeRequest request) {
            return base.Channel.geDetailsFromBarcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeResponse> geDetailsFromBarcodeAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string barcode, string _journal) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGeDetailsFromBarcodeRequest();
            inValue.CallContext = CallContext;
            inValue.barcode = barcode;
            inValue._journal = _journal;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).geDetailsFromBarcodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getOpenTagCountJournals(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsRequest request) {
            return base.Channel.getOpenTagCountJournals(request);
        }
        
        public string getOpenTagCountJournals(SafaItemDetails.SafaItemDetailsService.CallContext CallContext) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsRequest();
            inValue.CallContext = CallContext;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getOpenTagCountJournals(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getOpenTagCountJournalsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsRequest request) {
            return base.Channel.getOpenTagCountJournalsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsResponse> getOpenTagCountJournalsAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetOpenTagCountJournalsRequest();
            inValue.CallContext = CallContext;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getOpenTagCountJournalsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.SafaCreateEmployee(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeRequest request) {
            return base.Channel.SafaCreateEmployee(request);
        }
        
        public string SafaCreateEmployee(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string empId, string firstName, string middleName, string lastName, string dob, string joiningDate, bool isRetail) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeRequest();
            inValue.CallContext = CallContext;
            inValue.empId = empId;
            inValue.firstName = firstName;
            inValue.middleName = middleName;
            inValue.lastName = lastName;
            inValue.dob = dob;
            inValue.joiningDate = joiningDate;
            inValue.isRetail = isRetail;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).SafaCreateEmployee(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.SafaCreateEmployeeAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeRequest request) {
            return base.Channel.SafaCreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeResponse> SafaCreateEmployeeAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string empId, string firstName, string middleName, string lastName, string dob, string joiningDate, bool isRetail) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceSafaCreateEmployeeRequest();
            inValue.CallContext = CallContext;
            inValue.empId = empId;
            inValue.firstName = firstName;
            inValue.middleName = middleName;
            inValue.lastName = lastName;
            inValue.dob = dob;
            inValue.joiningDate = joiningDate;
            inValue.isRetail = isRetail;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).SafaCreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getCustomerPoints(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsRequest request) {
            return base.Channel.getCustomerPoints(request);
        }
        
        public string getCustomerPoints(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _cust) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsRequest();
            inValue.CallContext = CallContext;
            inValue._cust = _cust;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getCustomerPoints(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getCustomerPointsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsRequest request) {
            return base.Channel.getCustomerPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsResponse> getCustomerPointsAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _cust) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetCustomerPointsRequest();
            inValue.CallContext = CallContext;
            inValue._cust = _cust;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getCustomerPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getAllItems(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsRequest request) {
            return base.Channel.getAllItems(request);
        }
        
        public string getAllItems(SafaItemDetails.SafaItemDetailsService.CallContext CallContext) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsRequest();
            inValue.CallContext = CallContext;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getAllItems(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getAllItemsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsRequest request) {
            return base.Channel.getAllItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsResponse> getAllItemsAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetAllItemsRequest();
            inValue.CallContext = CallContext;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getAllItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getItemDetails(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsRequest request) {
            return base.Channel.getItemDetails(request);
        }
        
        public string getItemDetails(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string itemId) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsRequest();
            inValue.CallContext = CallContext;
            inValue.itemId = itemId;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getItemDetails(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.getItemDetailsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsRequest request) {
            return base.Channel.getItemDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsResponse> getItemDetailsAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string itemId) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceGetItemDetailsRequest();
            inValue.CallContext = CallContext;
            inValue.itemId = itemId;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).getItemDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.CreateTagCountLine(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineRequest request) {
            return base.Channel.CreateTagCountLine(request);
        }
        
        public string CreateTagCountLine(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string journalNum, string _item, string _barcode, decimal _qty, string _batch) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineRequest();
            inValue.CallContext = CallContext;
            inValue.journalNum = journalNum;
            inValue._item = _item;
            inValue._barcode = _barcode;
            inValue._qty = _qty;
            inValue._batch = _batch;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).CreateTagCountLine(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.CreateTagCountLineAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineRequest request) {
            return base.Channel.CreateTagCountLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineResponse> CreateTagCountLineAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string journalNum, string _item, string _barcode, decimal _qty, string _batch) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateTagCountLineRequest();
            inValue.CallContext = CallContext;
            inValue.journalNum = journalNum;
            inValue._item = _item;
            inValue._barcode = _barcode;
            inValue._qty = _qty;
            inValue._batch = _batch;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).CreateTagCountLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.earnOrRedeemPoints(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsRequest request) {
            return base.Channel.earnOrRedeemPoints(request);
        }
        
        public string earnOrRedeemPoints(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _cust, string _type, string _points, string _webOrderId) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsRequest();
            inValue.CallContext = CallContext;
            inValue._cust = _cust;
            inValue._type = _type;
            inValue._points = _points;
            inValue._webOrderId = _webOrderId;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).earnOrRedeemPoints(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.earnOrRedeemPointsAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsRequest request) {
            return base.Channel.earnOrRedeemPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsResponse> earnOrRedeemPointsAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string _cust, string _type, string _points, string _webOrderId) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceEarnOrRedeemPointsRequest();
            inValue.CallContext = CallContext;
            inValue._cust = _cust;
            inValue._type = _type;
            inValue._points = _points;
            inValue._webOrderId = _webOrderId;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).earnOrRedeemPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeResponse SafaItemDetails.SafaItemDetailsService.ItemDetailsService.CreateEmployee(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public string CreateEmployee(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string empId, string firstName, string middleName, string lastName, string dob, string joiningDate, bool isRetail) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeRequest();
            inValue.CallContext = CallContext;
            inValue.empId = empId;
            inValue.firstName = firstName;
            inValue.middleName = middleName;
            inValue.lastName = lastName;
            inValue.dob = dob;
            inValue.joiningDate = joiningDate;
            inValue.isRetail = isRetail;
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeResponse retVal = ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).CreateEmployee(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeResponse> SafaItemDetails.SafaItemDetailsService.ItemDetailsService.CreateEmployeeAsync(SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeResponse> CreateEmployeeAsync(SafaItemDetails.SafaItemDetailsService.CallContext CallContext, string empId, string firstName, string middleName, string lastName, string dob, string joiningDate, bool isRetail) {
            SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeRequest inValue = new SafaItemDetails.SafaItemDetailsService.ItemDetailsServiceCreateEmployeeRequest();
            inValue.CallContext = CallContext;
            inValue.empId = empId;
            inValue.firstName = firstName;
            inValue.middleName = middleName;
            inValue.lastName = lastName;
            inValue.dob = dob;
            inValue.joiningDate = joiningDate;
            inValue.isRetail = isRetail;
            return ((SafaItemDetails.SafaItemDetailsService.ItemDetailsService)(this)).CreateEmployeeAsync(inValue);
        }
    }
}
