//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafaItemDetails.NTServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonAsUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SafaItemDetails.NTServiceRef.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SafaItemDetails.NTServiceRef.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SafaItemDetails.NTServiceRef.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SafaItemDetails.NTServiceRef.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SafaItemDetails.NTServiceRef.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SafaItemDetails.NTServiceRef.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SafaItemDetails.NTServiceRef.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SafaItemDetails.NTServiceRef.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="NTServiceRef.ItemDetailsService")]
    public interface ItemDetailsService {
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGetOpenTagCountJournalsRequest) of message ItemDetailsServiceGetOpenTagCountJournalsRequest does not match the default value (getOpenTagCountJournals)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getOpenTagCountJournals", ReplyAction="http://tempuri.org/ItemDetailsService/getOpenTagCountJournalsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.NTServiceRef.AifFault), Action="http://tempuri.org/ItemDetailsService/getOpenTagCountJournalsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsResponse getOpenTagCountJournals(SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getOpenTagCountJournals", ReplyAction="http://tempuri.org/ItemDetailsService/getOpenTagCountJournalsResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsResponse> getOpenTagCountJournalsAsync(SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGeDetailsFromBarcodeRequest) of message ItemDetailsServiceGeDetailsFromBarcodeRequest does not match the default value (geDetailsFromBarcode)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/geDetailsFromBarcode", ReplyAction="http://tempuri.org/ItemDetailsService/geDetailsFromBarcodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.NTServiceRef.AifFault), Action="http://tempuri.org/ItemDetailsService/geDetailsFromBarcodeAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeResponse geDetailsFromBarcode(SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/geDetailsFromBarcode", ReplyAction="http://tempuri.org/ItemDetailsService/geDetailsFromBarcodeResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeResponse> geDetailsFromBarcodeAsync(SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceGetItemBatchesRequest) of message ItemDetailsServiceGetItemBatchesRequest does not match the default value (getItemBatches)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getItemBatches", ReplyAction="http://tempuri.org/ItemDetailsService/getItemBatchesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.NTServiceRef.AifFault), Action="http://tempuri.org/ItemDetailsService/getItemBatchesAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesResponse getItemBatches(SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/getItemBatches", ReplyAction="http://tempuri.org/ItemDetailsService/getItemBatchesResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesResponse> getItemBatchesAsync(SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ItemDetailsServiceCreateTagCountLineRequest) of message ItemDetailsServiceCreateTagCountLineRequest does not match the default value (CreateTagCountLine)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/CreateTagCountLine", ReplyAction="http://tempuri.org/ItemDetailsService/CreateTagCountLineResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafaItemDetails.NTServiceRef.AifFault), Action="http://tempuri.org/ItemDetailsService/CreateTagCountLineAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineResponse CreateTagCountLine(SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemDetailsService/CreateTagCountLine", ReplyAction="http://tempuri.org/ItemDetailsService/CreateTagCountLineResponse")]
        System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineResponse> CreateTagCountLineAsync(SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetOpenTagCountJournalsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetOpenTagCountJournalsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.NTServiceRef.CallContext CallContext;
        
        public ItemDetailsServiceGetOpenTagCountJournalsRequest() {
        }
        
        public ItemDetailsServiceGetOpenTagCountJournalsRequest(SafaItemDetails.NTServiceRef.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetOpenTagCountJournalsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetOpenTagCountJournalsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGetOpenTagCountJournalsResponse() {
        }
        
        public ItemDetailsServiceGetOpenTagCountJournalsResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGeDetailsFromBarcodeRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGeDetailsFromBarcodeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.NTServiceRef.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string barcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _journal;
        
        public ItemDetailsServiceGeDetailsFromBarcodeRequest() {
        }
        
        public ItemDetailsServiceGeDetailsFromBarcodeRequest(SafaItemDetails.NTServiceRef.CallContext CallContext, string barcode, string _journal) {
            this.CallContext = CallContext;
            this.barcode = barcode;
            this._journal = _journal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGeDetailsFromBarcodeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGeDetailsFromBarcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGeDetailsFromBarcodeResponse() {
        }
        
        public ItemDetailsServiceGeDetailsFromBarcodeResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetItemBatchesRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetItemBatchesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.NTServiceRef.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _item;
        
        public ItemDetailsServiceGetItemBatchesRequest() {
        }
        
        public ItemDetailsServiceGetItemBatchesRequest(SafaItemDetails.NTServiceRef.CallContext CallContext, string _item) {
            this.CallContext = CallContext;
            this._item = _item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceGetItemBatchesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceGetItemBatchesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceGetItemBatchesResponse() {
        }
        
        public ItemDetailsServiceGetItemBatchesResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceCreateTagCountLineRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceCreateTagCountLineRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public SafaItemDetails.NTServiceRef.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string journalNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _item;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _barcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public decimal _qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string _batch;
        
        public ItemDetailsServiceCreateTagCountLineRequest() {
        }
        
        public ItemDetailsServiceCreateTagCountLineRequest(SafaItemDetails.NTServiceRef.CallContext CallContext, string journalNum, string _item, string _barcode, decimal _qty, string _batch) {
            this.CallContext = CallContext;
            this.journalNum = journalNum;
            this._item = _item;
            this._barcode = _barcode;
            this._qty = _qty;
            this._batch = _batch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemDetailsServiceCreateTagCountLineResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ItemDetailsServiceCreateTagCountLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public ItemDetailsServiceCreateTagCountLineResponse() {
        }
        
        public ItemDetailsServiceCreateTagCountLineResponse(string response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItemDetailsServiceChannel : SafaItemDetails.NTServiceRef.ItemDetailsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemDetailsServiceClient : System.ServiceModel.ClientBase<SafaItemDetails.NTServiceRef.ItemDetailsService>, SafaItemDetails.NTServiceRef.ItemDetailsService {
        
        public ItemDetailsServiceClient() {
        }
        
        public ItemDetailsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemDetailsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemDetailsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsResponse SafaItemDetails.NTServiceRef.ItemDetailsService.getOpenTagCountJournals(SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsRequest request) {
            return base.Channel.getOpenTagCountJournals(request);
        }
        
        public string getOpenTagCountJournals(SafaItemDetails.NTServiceRef.CallContext CallContext) {
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsRequest inValue = new SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsRequest();
            inValue.CallContext = CallContext;
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsResponse retVal = ((SafaItemDetails.NTServiceRef.ItemDetailsService)(this)).getOpenTagCountJournals(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsResponse> SafaItemDetails.NTServiceRef.ItemDetailsService.getOpenTagCountJournalsAsync(SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsRequest request) {
            return base.Channel.getOpenTagCountJournalsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsResponse> getOpenTagCountJournalsAsync(SafaItemDetails.NTServiceRef.CallContext CallContext) {
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsRequest inValue = new SafaItemDetails.NTServiceRef.ItemDetailsServiceGetOpenTagCountJournalsRequest();
            inValue.CallContext = CallContext;
            return ((SafaItemDetails.NTServiceRef.ItemDetailsService)(this)).getOpenTagCountJournalsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeResponse SafaItemDetails.NTServiceRef.ItemDetailsService.geDetailsFromBarcode(SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeRequest request) {
            return base.Channel.geDetailsFromBarcode(request);
        }
        
        public string geDetailsFromBarcode(SafaItemDetails.NTServiceRef.CallContext CallContext, string barcode, string _journal) {
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeRequest inValue = new SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeRequest();
            inValue.CallContext = CallContext;
            inValue.barcode = barcode;
            inValue._journal = _journal;
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeResponse retVal = ((SafaItemDetails.NTServiceRef.ItemDetailsService)(this)).geDetailsFromBarcode(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeResponse> SafaItemDetails.NTServiceRef.ItemDetailsService.geDetailsFromBarcodeAsync(SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeRequest request) {
            return base.Channel.geDetailsFromBarcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeResponse> geDetailsFromBarcodeAsync(SafaItemDetails.NTServiceRef.CallContext CallContext, string barcode, string _journal) {
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeRequest inValue = new SafaItemDetails.NTServiceRef.ItemDetailsServiceGeDetailsFromBarcodeRequest();
            inValue.CallContext = CallContext;
            inValue.barcode = barcode;
            inValue._journal = _journal;
            return ((SafaItemDetails.NTServiceRef.ItemDetailsService)(this)).geDetailsFromBarcodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesResponse SafaItemDetails.NTServiceRef.ItemDetailsService.getItemBatches(SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesRequest request) {
            return base.Channel.getItemBatches(request);
        }
        
        public string getItemBatches(SafaItemDetails.NTServiceRef.CallContext CallContext, string _item) {
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesRequest inValue = new SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesRequest();
            inValue.CallContext = CallContext;
            inValue._item = _item;
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesResponse retVal = ((SafaItemDetails.NTServiceRef.ItemDetailsService)(this)).getItemBatches(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesResponse> SafaItemDetails.NTServiceRef.ItemDetailsService.getItemBatchesAsync(SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesRequest request) {
            return base.Channel.getItemBatchesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesResponse> getItemBatchesAsync(SafaItemDetails.NTServiceRef.CallContext CallContext, string _item) {
            SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesRequest inValue = new SafaItemDetails.NTServiceRef.ItemDetailsServiceGetItemBatchesRequest();
            inValue.CallContext = CallContext;
            inValue._item = _item;
            return ((SafaItemDetails.NTServiceRef.ItemDetailsService)(this)).getItemBatchesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineResponse SafaItemDetails.NTServiceRef.ItemDetailsService.CreateTagCountLine(SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineRequest request) {
            return base.Channel.CreateTagCountLine(request);
        }
        
        public string CreateTagCountLine(SafaItemDetails.NTServiceRef.CallContext CallContext, string journalNum, string _item, string _barcode, decimal _qty, string _batch) {
            SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineRequest inValue = new SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineRequest();
            inValue.CallContext = CallContext;
            inValue.journalNum = journalNum;
            inValue._item = _item;
            inValue._barcode = _barcode;
            inValue._qty = _qty;
            inValue._batch = _batch;
            SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineResponse retVal = ((SafaItemDetails.NTServiceRef.ItemDetailsService)(this)).CreateTagCountLine(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineResponse> SafaItemDetails.NTServiceRef.ItemDetailsService.CreateTagCountLineAsync(SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineRequest request) {
            return base.Channel.CreateTagCountLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineResponse> CreateTagCountLineAsync(SafaItemDetails.NTServiceRef.CallContext CallContext, string journalNum, string _item, string _barcode, decimal _qty, string _batch) {
            SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineRequest inValue = new SafaItemDetails.NTServiceRef.ItemDetailsServiceCreateTagCountLineRequest();
            inValue.CallContext = CallContext;
            inValue.journalNum = journalNum;
            inValue._item = _item;
            inValue._barcode = _barcode;
            inValue._qty = _qty;
            inValue._batch = _batch;
            return ((SafaItemDetails.NTServiceRef.ItemDetailsService)(this)).CreateTagCountLineAsync(inValue);
        }
    }
}
